# encoding: UTF-8

blur_translations = {
  "en" => "Mask",
  "ar" => "قناع",
  "zh-Hans" => "遮罩",
  "fr" => "Masque",
  "de" => "Maske",
  "hi" => "मास्क",
  "ja" => "マスク",
  "pt" => "Máscara",
  "ru" => "Маска",
  "es" => "Máscara"
}

tooltips = {
  "ar" => {
    "settings.language.tooltip" => "تعيين لغة واجهة التطبيق.",
    "settings.languagePopup.tooltip" => "اختر لغتك المفضلة. النظام الافتراضي سيتطابق مع لغة جهازك.",
    "settings.launch.tooltip" => "بدء التطبيق تلقائياً عند تسجيل الدخول.",
    "settings.launchCheckbox.tooltip" => "قم بتمكين هذا حتى لا تضطر إلى فتح التطبيق يدوياً.",
    "settings.autoSave.tooltip" => "حفظ جميع اللقطات تلقائيًا دون سؤال.",
    "settings.autoSaveCheckbox.tooltip" => "يتخطى مربع الحوار ويحفظ اللقطات مباشرة في المجلد المحدد.",
    "settings.location.tooltip" => "المجلد الذي سيتم حفظ اللقطات فيه.",
    "settings.pathControl.tooltip" => "يعرض مسار المجلد الحالي.",
    "settings.changeButton.tooltip" => "انقر لتحديد مجلد مختلف.",
    "settings.format.tooltip" => "صيغة الملف للقطات المحفوظة.",
    "settings.formatPopup.tooltip" => "اختر PNG للحصول على أعلى جودة أو JPEG لتقليل حجم الملف.",
    "settings.freezeScreen.tooltip" => "تجميد الشاشة فور بدء الالتقاط.",
    "settings.freezeScreenCheckbox.tooltip" => "عند التفعيل، تتجمد الشاشة لالتقاط القوائم المؤقتة.",
    "settings.notifications.tooltip" => "تشغيل صوت عند نجاح التقاط الشاشة.",
    "settings.soundsCheckbox.tooltip" => "تفعيل أو تعطيل صوت كاميرا الالتقاط.",
    "settings.opacity.tooltip" => "تعيين الشفافية الافتراضية للقطات الجديدة.",
    "settings.slider.tooltip" => "اسحب لضبط الشفافية.",
    "settings.neon.tooltip" => "إضافة توهج ملون حول اللقطات.",
    "settings.neonCheckbox.tooltip" => "يضيف إطار متوهج للقطات. يتم التحكم باللون من إعداد السمات.",
    "settings.theme.tooltip" => "اختر مظهرا مرئيا للتطبيق.",
    "settings.themePopup.tooltip" => "يغير لون التوهج — Cyberpunk، Matrix، أو Solar.",
    "settings.click.tooltip" => "كيف يعمل النقر على اللقطة.",
    "settings.clickPopup.tooltip" => "نقرة واحدة تغلق اللقطة فوراً. النقر المزدوج يقلل من الإغلاق العرضي.",
    "settings.magic.tooltip" => "إظهار/إخفاء اللقطات تلقائياً بناءً على التطبيق النشط.",
    "settings.magicCheckbox.tooltip" => "يظهر اللقطة فقط عند تفعيل التطبيق المرتبط بها.",
    "settings.advancedTools.tooltip" => "تحكم في الأدوات التي تظهر في قائمة النقر بزر الماوس الأيمن.",
    "settings.magnifyCheckbox.tooltip" => "إظهار أداة التكبير.",
    "settings.grayscaleCheckbox.tooltip" => "إظهار مرشح الأبيض والأسود.",
    "settings.rulersCheckbox.tooltip" => "إظهار أداة المساطر.",
    "settings.colorPickerCheckbox.tooltip" => "إظهار أداة تحديد الألوان.",
    "settings.ghostModeCheckbox.tooltip" => "إظهار وضع الشبح للتفاعل مع النوافذ الخلفية."
  },
  "zh-Hans" => {
    "settings.language.tooltip" => "设置应用程序界面的语言。",
    "settings.languagePopup.tooltip" => "选择您偏好的语言。系统默认将匹配您Mac的语言。",
    "settings.launch.tooltip" => "登录时自动启动程序。",
    "settings.launchCheckbox.tooltip" => "启用此功能，您就无需每次手动打开应用。",
    "settings.autoSave.tooltip" => "自动保存所有截图，不需询问。",
    "settings.autoSaveCheckbox.tooltip" => "启用后，截图将跳过保存对话框直接进入保存文件夹。",
    "settings.location.tooltip" => "保存截图的文件夹。",
    "settings.pathControl.tooltip" => "显示保存图像的当前文件夹路径。",
    "settings.changeButton.tooltip" => "点击选择其他文件夹保存截图。",
    "settings.format.tooltip" => "保存截图的文件格式。",
    "settings.formatPopup.tooltip" => "选择 PNG 获取最高质量和透明度，选择 JPEG 以减小文件大小。",
    "settings.freezeScreen.tooltip" => "开始截图时立即冻结屏幕。",
    "settings.freezeScreenCheckbox.tooltip" => "启用后，屏幕立即冻结以捕捉悬浮菜单。",
    "settings.notifications.tooltip" => "截图成功后播放声音。",
    "settings.soundsCheckbox.tooltip" => "启用或禁用相机快门声音。",
    "settings.opacity.tooltip" => "设置新截图的默认透明度。",
    "settings.slider.tooltip" => "拖动以调整透明度。值越低，截图越透明。",
    "settings.neon.tooltip" => "为截图添加发光边框。",
    "settings.neonCheckbox.tooltip" => "启用后，截图将具有明亮的发光边框。发光颜色受主题设置控制。",
    "settings.theme.tooltip" => "选择应用的视觉主题。",
    "settings.themePopup.tooltip" => "更改霓虹灯边框发光颜色 — Cyberpunk（青色），Matrix（绿色）或 Solar（橙色）。",
    "settings.click.tooltip" => "点击截图时的行为。",
    "settings.clickPopup.tooltip" => "单击立即关闭截图。双击需要两次点击以关闭，减少意外关闭的情况。",
    "settings.magic.tooltip" => "根据活动应用自动显示/隐藏截图。",
    "settings.magicCheckbox.tooltip" => "启用后，可以固定截图。只有关联的应用程序在前台时，截图才会出现。",
    "settings.advancedTools.tooltip" => "控制哪些工具出现在右键菜单中。",
    "settings.magnifyCheckbox.tooltip" => "在菜单中显示放大镜工具以查看像素级细节。",
    "settings.grayscaleCheckbox.tooltip" => "在菜单中显示灰度滤镜以黑白形式查看截图。",
    "settings.rulersCheckbox.tooltip" => "在菜单中显示标尺工具以测量距离和对齐。",
    "settings.colorPickerCheckbox.tooltip" => "在菜单中显示拾色器工具。",
    "settings.ghostModeCheckbox.tooltip" => "在菜单中显示幽灵模式，使截图可穿透点击。"
  },
  "fr" => {
    "settings.language.tooltip" => "Définir la langue de l'interface de l'application.",
    "settings.languagePopup.tooltip" => "Choisissez votre langue préférée. La valeur par défaut du système correspondra à la langue de votre Mac.",
    "settings.launch.tooltip" => "Démarrer automatiquement lors de votre connexion.",
    "settings.launchCheckbox.tooltip" => "Activez cette option pour ne pas avoir à ouvrir l'application manuellement.",
    "settings.autoSave.tooltip" => "Enregistrer automatiquement toutes les captures d'écran sans demander.",
    "settings.autoSaveCheckbox.tooltip" => "Lorsqu'il est activé, les captures d'écran contournent la boîte de dialogue d'enregistrement.",
    "settings.location.tooltip" => "Le dossier où vos captures d'écran seront enregistrées.",
    "settings.pathControl.tooltip" => "Affiche le chemin du dossier actuel où vos images sont enregistrées.",
    "settings.changeButton.tooltip" => "Cliquez pour sélectionner un dossier différent pour enregistrer vos captures d'écran.",
    "settings.format.tooltip" => "Format de fichier pour vos captures d'écran enregistrées.",
    "settings.formatPopup.tooltip" => "Choisissez le PNG pour une qualité maximale ou JPEG pour des fichiers plus petits.",
    "settings.freezeScreen.tooltip" => "Figer immédiatement l'écran au lancement de la capture.",
    "settings.freezeScreenCheckbox.tooltip" => "S'il est activé, l'écran se fige immédiatement pour capturer les menus éphémères.",
    "settings.notifications.tooltip" => "Jouer un son lorsqu'une capture d'écran est réussie.",
    "settings.soundsCheckbox.tooltip" => "Activer ou désactiver le son de l'obturateur.",
    "settings.opacity.tooltip" => "Définir la transparence par défaut des nouvelles captures d'écran.",
    "settings.slider.tooltip" => "Faites glisser pour ajuster l'opacité.",
    "settings.neon.tooltip" => "Ajouter une bordure lumineuse autour des captures d'écran.",
    "settings.neonCheckbox.tooltip" => "La couleur est contrôlée par le paramètre de Thème.",
    "settings.theme.tooltip" => "Choisir un thème visuel pour l'application.",
    "settings.themePopup.tooltip" => "Modifie la couleur de la bordure lumineuse.",
    "settings.click.tooltip" => "Comportement du clic sur une capture d'écran.",
    "settings.clickPopup.tooltip" => "Un clic ferme immédiatement la capture. Le double clic réduit les fermetures accidentelles.",
    "settings.magic.tooltip" => "Afficher/Masquer automatiquement les captures d'écran.",
    "settings.magicCheckbox.tooltip" => "Lorsqu'il est activé, les captures n'apparaissent que si l'application associée est au premier plan.",
    "settings.advancedTools.tooltip" => "Contrôler les outils apparaissant dans le menu contextuel.",
    "settings.magnifyCheckbox.tooltip" => "Afficher la Loupe.",
    "settings.grayscaleCheckbox.tooltip" => "Afficher le filtre Nuances de Gris.",
    "settings.rulersCheckbox.tooltip" => "Afficher l'outil Règles.",
    "settings.colorPickerCheckbox.tooltip" => "Afficher la Pipe à couleur.",
    "settings.ghostModeCheckbox.tooltip" => "Afficher le mode Fantôme (clic au travers)."
  },
  "de" => {
    "settings.language.tooltip" => "Sprache der Benutzeroberfläche festlegen.",
    "settings.languagePopup.tooltip" => "Wählen Sie Ihre bevorzugte Sprache.",
    "settings.launch.tooltip" => "Automatischer Start beim Anmelden.",
    "settings.launchCheckbox.tooltip" => "Aktivieren Sie dies, um die App nicht jedes Mal manuell öffnen zu müssen.",
    "settings.autoSave.tooltip" => "Alle Screenshots automatisch speichern.",
    "settings.autoSaveCheckbox.tooltip" => "Speichert Screenshots direkt in Ihrem Ordner, ohne nachzufragen.",
    "settings.location.tooltip" => "Der Ordner für Ihre Screenshots.",
    "settings.pathControl.tooltip" => "Zeigt den aktuellen Ordnerpfad an.",
    "settings.changeButton.tooltip" => "Klicken, um einen anderen Ordner auszuwählen.",
    "settings.format.tooltip" => "Dateiformat für Ihre Screenshots.",
    "settings.formatPopup.tooltip" => "Wählen Sie PNG für höchste Qualität oder JPEG für kleine Dateigrößen.",
    "settings.freezeScreen.tooltip" => "Bildschirm beim Start der Aufnahme einfrieren.",
    "settings.freezeScreenCheckbox.tooltip" => "Wenn aktiviert, friert der Bildschirm sofort ein.",
    "settings.notifications.tooltip" => "Ton abspielen, wenn ein Screenshot gemacht wurde.",
    "settings.soundsCheckbox.tooltip" => "Kamera-Auslösegeräusch aktivieren/deaktivieren.",
    "settings.opacity.tooltip" => "Standardtransparenz neuer Screenshots festlegen.",
    "settings.slider.tooltip" => "Ziehen, um die Deckkraft anzupassen.",
    "settings.neon.tooltip" => "Leuchtenden Rand hinzufügen.",
    "settings.neonCheckbox.tooltip" => "Fügt einen Neonrand hinzu, die Farbe ist themenabhängig.",
    "settings.theme.tooltip" => "Visuelles Thema wählen.",
    "settings.themePopup.tooltip" => "Ändert die Neonrandfarbe.",
    "settings.click.tooltip" => "Verhalten beim Klicken.",
    "settings.clickPopup.tooltip" => "Einzelklick schließt den Screenshot. Doppelklick verhindert versehentliches Schließen.",
    "settings.magic.tooltip" => "Screenshots basierend auf App-Sichtbarkeit ein-/ausblenden.",
    "settings.magicCheckbox.tooltip" => "Nützlich, um Screenshots nach Apps zu pinnen.",
    "settings.advancedTools.tooltip" => "Einstellungen für das Rechtsklick-Menü.",
    "settings.magnifyCheckbox.tooltip" => "Lupe (Vergrößerung) anzeigen.",
    "settings.grayscaleCheckbox.tooltip" => "Graustufen-Filter anzeigen.",
    "settings.rulersCheckbox.tooltip" => "Lineale anzeigen.",
    "settings.colorPickerCheckbox.tooltip" => "Pipette anzeigen.",
    "settings.ghostModeCheckbox.tooltip" => "Geist-Modus (Klick-durch) anzeigen."
  },
  "hi" => {
    "settings.language.tooltip" => "ऐप्लिकेशन इंटरफ़ेस के लिए भाषा सेट करें।",
    "settings.languagePopup.tooltip" => "अपनी पसंदीदा भाषा चुनें। सिस्टम डिफ़ॉल्ट आपके मैक की भाषा से मेल खाएगा।",
    "settings.launch.tooltip" => "लॉग इन करते समय ऐप को स्वचालित रूप से शुरू करें।",
    "settings.launchCheckbox.tooltip" => "इसे सक्षम करें ताकि आपको बार-बार मैन्युअल रूप से ऐप खोलने की आवश्यकता न हो।",
    "settings.autoSave.tooltip" => "बिना पूछे सभी स्क्रीनशॉट स्वचालित रूप से सहेजें।",
    "settings.autoSaveCheckbox.tooltip" => "सक्षम होने पर, स्क्रीनशॉट संवाद को छोड़ देते हैं और सीधे आपके सहेजे गए फ़ोल्डर में जाते हैं।",
    "settings.location.tooltip" => "वह फ़ोल्डर जहाँ आपके स्क्रीनशॉट सहेजे जाएँगे।",
    "settings.pathControl.tooltip" => "वर्तमान फ़ोल्डर पथ दिखाता है जहाँ आपके चित्र सहेजे जा रहे हैं।",
    "settings.changeButton.tooltip" => "स्क्रीनशॉट सहेजने के लिए एक अलग फ़ोल्डर चुनने के लिए क्लिक करें।",
    "settings.format.tooltip" => "आपके सहेजे गए स्क्रीनशॉट के लिए फ़ाइल प्रारूप।",
    "settings.formatPopup.tooltip" => "उच्चतम गुणवत्ता और पारदर्शिता के लिए PNG, या छोटे फ़ाइल आकार के लिए JPEG चुनें।",
    "settings.freezeScreen.tooltip" => "जैसे ही आप स्क्रीनशॉट शुरू करते हैं, स्क्रीन को तुरंत फ़्रीज़ करें।",
    "settings.freezeScreenCheckbox.tooltip" => "यदि सक्षम किया जाता है, तो मेनू कैप्चर करने के लिए स्क्रीन तुरंत फ़्रीज़ हो जाती है।",
    "settings.notifications.tooltip" => "स्क्रीनशॉट सफलतापूर्वक कैप्चर होने पर एक ऑडियो चलाएं।",
    "settings.soundsCheckbox.tooltip" => "कैमरा शटर ध्वनि को सक्षम या अक्षम करें।",
    "settings.opacity.tooltip" => "नए स्क्रीनशॉट के लिए डिफ़ॉल्ट पारदर्शिता सेट करें।",
    "settings.slider.tooltip" => "पारदर्शिता को समायोजित करने के लिए खींचें।",
    "settings.neon.tooltip" => "स्क्रीनशॉट के चारों ओर एक रंगीन चमक जोड़ें।",
    "settings.neonCheckbox.tooltip" => "सक्षम होने पर, स्क्रीनशॉट में एक चमकदार नियॉन सीमा होगी।",
    "settings.theme.tooltip" => "ऐप के लिए एक दृश्य विषय चुनें।",
    "settings.themePopup.tooltip" => "निऑन बॉर्डर रंग बदलता है।",
    "settings.click.tooltip" => "स्क्रीनशॉट पर क्लिक करने पर क्या होता है।",
    "settings.clickPopup.tooltip" => "एक क्लिक स्क्रीनशॉट को तुरंत बंद कर देता है। दोहरे क्लिक से आकस्मिक बंद होने से बचाव होता है।",
    "settings.magic.tooltip" => "सक्रिय एप्लिकेशन के आधार पर स्वचालित रूप से स्क्रीनशॉट दिखाएं/छिपाएं।",
    "settings.magicCheckbox.tooltip" => "सक्षम होने पर, आप स्क्रीनशॉट को विशिष्ट ऐप्स पर पिन कर सकते हैं।",
    "settings.advancedTools.tooltip" => "नियंत्रित करें कि राइट-क्लिक संदर्भ मेनू में कौन से टूल दिखाई देते हैं।",
    "settings.magnifyCheckbox.tooltip" => "पिक्सेल-स्तर पर ज़ूम करने के लिए मैग्निफाई टूल दिखाएं।",
    "settings.grayscaleCheckbox.tooltip" => "स्क्रीनशॉट को काले-सफेद में देखने के लिए ग्रैस्केल फ़िल्टर दिखाएं।",
    "settings.rulersCheckbox.tooltip" => "दूरी मापने और अलाइनमेंट के लिए रूलर टूल दिखाएं।",
    "settings.colorPickerCheckbox.tooltip" => "स्क्रीनशॉट से रंग कॉपी करने के लिए कलर पिकर टूल दिखाएं।",
    "settings.ghostModeCheckbox.tooltip" => "घोस्ट मोड दिखाएं (पीछे के विंडो के साथ इंटरैक्ट करने के लिए)।"
  },
  "ja" => {
    "settings.language.tooltip" => "アプリの言語を設定します。",
    "settings.languagePopup.tooltip" => "お好みの言語を選択してください。",
    "settings.launch.tooltip" => "ログイン時に自動的に起動します。",
    "settings.launchCheckbox.tooltip" => "これを有効にすると、毎回手動でアプリを開く必要がなくなります。",
    "settings.autoSave.tooltip" => "質問なしにスクリーンショットを自動保存します。",
    "settings.autoSaveCheckbox.tooltip" => "有効にすると、保存ダイアログをスキップして直接保存フォルダに移動します。",
    "settings.location.tooltip" => "スクリーンショットが保存されるフォルダ。",
    "settings.pathControl.tooltip" => "保存先のフォルダパスを表示します。",
    "settings.changeButton.tooltip" => "スクリーンショットを保存する別のフォルダを選択します。",
    "settings.format.tooltip" => "ファイル形式を設定します。",
    "settings.formatPopup.tooltip" => "最高画質と透過性を優先ならPNG、サイズ重視ならJPEGを選択します。",
    "settings.freezeScreen.tooltip" => "キャプチャ開始時に画面を瞬時に固定します。",
    "settings.freezeScreenCheckbox.tooltip" => "有効にすると、ホバーメニューなどをキャプチャするために画面がすぐ固定されます。",
    "settings.notifications.tooltip" => "キャプチャ成功時に音を鳴らします。",
    "settings.soundsCheckbox.tooltip" => "シャッター音を有効/無効にします。",
    "settings.opacity.tooltip" => "オーバーレイのデフォルトの透明度を設定します。",
    "settings.slider.tooltip" => "スライダーで不透明度を調整します。",
    "settings.neon.tooltip" => "カラフルな光る枠線を追加します。",
    "settings.neonCheckbox.tooltip" => "有効にすると輝く枠が表示され、テーマで色を設定できます。",
    "settings.theme.tooltip" => "視覚テーマを選択します。",
    "settings.themePopup.tooltip" => "ネオンボーダーの色を変更します。",
    "settings.click.tooltip" => "クリック時の動作を設定します。",
    "settings.clickPopup.tooltip" => "シングルクリックですぐ閉じるか、ダブルクリックのみ受け付けるか選択できます。",
    "settings.magic.tooltip" => "アクティブなアプリに応じて表示/非表示を自動化します。",
    "settings.magicCheckbox.tooltip" => "紐付けられたアプリが前面にある時のみ表示されます。",
    "settings.advancedTools.tooltip" => "右クリックメニューのツールを調整します。",
    "settings.magnifyCheckbox.tooltip" => "拡大鏡(ルーペ)を表示します。",
    "settings.grayscaleCheckbox.tooltip" => "グレースケール(白黒)フィルタを表示します。",
    "settings.rulersCheckbox.tooltip" => "定規ツールを表示します。",
    "settings.colorPickerCheckbox.tooltip" => "カラーピッカーツールを表示します。",
    "settings.ghostModeCheckbox.tooltip" => "クリックを背後のウィンドウに貫通させるゴーストモードを表示します。"
  },
  "pt" => {
    "settings.language.tooltip" => "Defina o idioma da interface.",
    "settings.languagePopup.tooltip" => "Escolha seu idioma preferido.",
    "settings.launch.tooltip" => "Iniciar automaticamente ao fazer login.",
    "settings.launchCheckbox.tooltip" => "Ative para não ter que abrir manualmente todas as vezes.",
    "settings.autoSave.tooltip" => "Salvar capturas automaticamente sem perguntar.",
    "settings.autoSaveCheckbox.tooltip" => "As capturas pulam a caixa de diálogo e vão direto para a pasta.",
    "settings.location.tooltip" => "A pasta onde suas capturas são salvas.",
    "settings.pathControl.tooltip" => "Mostra o caminho da pasta atual.",
    "settings.changeButton.tooltip" => "Clique para alterar a pasta de salvamento.",
    "settings.format.tooltip" => "O formato do arquivo salvo.",
    "settings.formatPopup.tooltip" => "Selecione PNG para melhor qualidade ou JPEG para economizar espaço.",
    "settings.freezeScreen.tooltip" => "Congela a tela no instante em que a captura inicia.",
    "settings.freezeScreenCheckbox.tooltip" => "Quando ativado, suspende animações imediatamente para pegar menus difíceis.",
    "settings.notifications.tooltip" => "Toca um som após o sucesso da captura.",
    "settings.soundsCheckbox.tooltip" => "Ativa/desativa o barulho da câmera.",
    "settings.opacity.tooltip" => "Transparência padrão de novas sobreposições.",
    "settings.slider.tooltip" => "Arraste para alterar a utilidade da transparência para ver as janelas de trás.",
    "settings.neon.tooltip" => "Borda brilhante ao redor.",
    "settings.neonCheckbox.tooltip" => "Garante uma borda neon dependendo do tema escolhido.",
    "settings.theme.tooltip" => "Escolha um tema visual.",
    "settings.themePopup.tooltip" => "Muda a cor da borda Neon.",
    "settings.click.tooltip" => "O comportamento do clique.",
    "settings.clickPopup.tooltip" => "Um clique apenas fecha imediatamente. O clique duplo evita fechar sem querer.",
    "settings.magic.tooltip" => "Configuração inteligente de Ocultar/Mostrar.",
    "settings.magicCheckbox.tooltip" => "Se ativado, fixa uma captura ao aplicativo pertinente.",
    "settings.advancedTools.tooltip" => "Menu de opções do botão direito.",
    "settings.magnifyCheckbox.tooltip" => "Mostrar Lupa de Zoom.",
    "settings.grayscaleCheckbox.tooltip" => "Mostrar filtro Escala de cinza.",
    "settings.rulersCheckbox.tooltip" => "Mostrar ferramenta Régua.",
    "settings.colorPickerCheckbox.tooltip" => "Mostrar conta-gotas de cores.",
    "settings.ghostModeCheckbox.tooltip" => "Mostrar modo Fantasma (clique através da janela)."
  },
  "ru" => {
    "settings.language.tooltip" => "Установить язык интерфейса приложения.",
    "settings.languagePopup.tooltip" => "Выберите предпочитаемый язык.",
    "settings.launch.tooltip" => "Запускать автоматически при входе.",
    "settings.launchCheckbox.tooltip" => "Включите, чтобы не открывать приложение вручную при каждом запуске компьютера.",
    "settings.autoSave.tooltip" => "Автоматически сохранять все снимки без подтверждения.",
    "settings.autoSaveCheckbox.tooltip" => "Если включено, снимки обходят диалог сохранения и сохраняются в выбранную папку.",
    "settings.location.tooltip" => "Папка для сохранения скриншотов.",
    "settings.pathControl.tooltip" => "Показывает текущий путь папки сохранения.",
    "settings.changeButton.tooltip" => "Нажмите, чтобы выбрать другую папку.",
    "settings.format.tooltip" => "Формат файла для сохраненных снимков.",
    "settings.formatPopup.tooltip" => "PNG для максимального качества или JPEG для меньшего размера файла.",
    "settings.freezeScreen.tooltip" => "Мгновенно замораживает экран при начале съемки.",
    "settings.freezeScreenCheckbox.tooltip" => "Замораживает экран чтобы снимать исчезающие элементы.",
    "settings.notifications.tooltip" => "Воспроизводить звук при успешном снимке.",
    "settings.soundsCheckbox.tooltip" => "Включить или отключить звук затвора.",
    "settings.opacity.tooltip" => "Установить по умолчанию прозрачность скриншота.",
    "settings.slider.tooltip" => "Перетащите, чтобы настроить непрозрачность.",
    "settings.neon.tooltip" => "Добавить цветное сияние вокруг скриншота.",
    "settings.neonCheckbox.tooltip" => "Цвет будет зависеть от выбранной темы.",
    "settings.theme.tooltip" => "Выбрать визуальную тему приложения.",
    "settings.themePopup.tooltip" => "Изменяет цвет неонового свечения.",
    "settings.click.tooltip" => "Поведение при нажатии на снимок.",
    "settings.clickPopup.tooltip" => "Одинарный клик сразу закрывает снимок. Двойной клик предотвращает случайные закрытия.",
    "settings.magic.tooltip" => "Автоматически скрывать/показывать снимки в зависимости от активного окна.",
    "settings.magicCheckbox.tooltip" => "Привязывает скриншоты к окнам определенных программ.",
    "settings.advancedTools.tooltip" => "Управлять инструментами меню правой кнопки мыши.",
    "settings.magnifyCheckbox.tooltip" => "Инструмент: Лупа.",
    "settings.grayscaleCheckbox.tooltip" => "Инструмент: Черно-белый фильтр.",
    "settings.rulersCheckbox.tooltip" => "Инструмент: Линейка.",
    "settings.colorPickerCheckbox.tooltip" => "Инструмент: Пипетка цветов.",
    "settings.ghostModeCheckbox.tooltip" => "Инструмент: Режим призрака."
  },
  "es" => {
    "settings.language.tooltip" => "Establecer el idioma de la interfaz de la aplicación.",
    "settings.languagePopup.tooltip" => "Elija su idioma preferido.",
    "settings.launch.tooltip" => "Iniciar automáticamente al iniciar sesión.",
    "settings.launchCheckbox.tooltip" => "Habilite esto para no tener que abrir la aplicación manualmente cada vez.",
    "settings.autoSave.tooltip" => "Guardar automáticamente todas las capturas de pantalla sin preguntar.",
    "settings.autoSaveCheckbox.tooltip" => "Al habilitarse, las capturas de pantalla van directamente a la carpeta elegida.",
    "settings.location.tooltip" => "La carpeta donde se guardarán sus capturas de pantalla.",
    "settings.pathControl.tooltip" => "Muestra la ruta de la carpeta actual.",
    "settings.changeButton.tooltip" => "Haga clic para seleccionar una carpeta diferente.",
    "settings.format.tooltip" => "El formato de archivo para sus capturas de pantalla.",
    "settings.formatPopup.tooltip" => "Elija PNG para conservar transparencia o JPEG para menor peso.",
    "settings.freezeScreen.tooltip" => "Congelar instantáneamente la pantalla al inicio.",
    "settings.freezeScreenCheckbox.tooltip" => "Fija menús e interacciones temporales.",
    "settings.notifications.tooltip" => "Reproducir un sonido cuando la captura es exitosa.",
    "settings.soundsCheckbox.tooltip" => "Habilitar o deshabilitar el sonido del obturador.",
    "settings.opacity.tooltip" => "Establecer la transparencia predeterminada de las nuevas capturas de pantalla.",
    "settings.slider.tooltip" => "Arrastre para ajustar la opacidad.",
    "settings.neon.tooltip" => "Agregar un borde brillante iluminado.",
    "settings.neonCheckbox.tooltip" => "Dependiendo de la configuración del tema.",
    "settings.theme.tooltip" => "Elegir un tema visual.",
    "settings.themePopup.tooltip" => "Cambia el color de iluminación neón.",
    "settings.click.tooltip" => "Comportamiento del clic en la pantalla.",
    "settings.clickPopup.tooltip" => "Clic simple cierra la captura de inmediato. Clic doble previene el cierre no deseado.",
    "settings.magic.tooltip" => "Ocultar/Mostrar automáticamente según la aplicación.",
    "settings.magicCheckbox.tooltip" => "Fija ciertas capturas a la aplicación actual.",
    "settings.advancedTools.tooltip" => "Controlar opciones del menú context.",
    "settings.magnifyCheckbox.tooltip" => "Mostrar herramienta de Lupa.",
    "settings.grayscaleCheckbox.tooltip" => "Mostrar herramienta de Escala de grises.",
    "settings.rulersCheckbox.tooltip" => "Mostrar herramienta de Reglas.",
    "settings.colorPickerCheckbox.tooltip" => "Mostrar Cuentagotas de color.",
    "settings.ghostModeCheckbox.tooltip" => "Modo fantasma (clic-a-través de fotos)."
  }
}

base_dir = "SilkySnip/Resources"

tooltips.each do |lang, keys|
  file_path = "#{base_dir}/#{lang}.lproj/Localizable.strings"
  next unless File.exist?(file_path)
  
  content = File.read(file_path)
  
  # Step 1: Add Tooltips if not present
  unless content.include?("settings.language.tooltip")
    append_str = "\n\n/* Tooltips */\n"
    keys.each { |k, v| append_str += "\"#{k}\" = \"#{v}\";\n" }
    content += append_str
  end
  
  # Step 2: Replace Blur with Mask translation
  mask_translation = blur_translations[lang] || "Mask"
  if content.include?("tool_blur")
    # Using regex to replace the right hand side String for tool_blur
    content.gsub!(/"tool_blur"\s*=\s*".*?";/, "\"tool_blur\" = \"#{mask_translation}\";")
  end
  
  File.write(file_path, content)
  puts "Injecting tooltips into #{lang}.lproj"
end

# Also fix the English file for the Blur to Mask rename
en_path = "#{base_dir}/en.lproj/Localizable.strings"
if File.exist?(en_path)
    en_content = File.read(en_path)
    en_content.gsub!(/"tool_blur"\s*=\s*".*?";/, "\"tool_blur\" = \"Mask\";")
    File.write(en_path, en_content)
    puts "Fixed English Blur to Mask"
end

